---
# Prolog tasks
- hosts: all
  tags: always
  become: true
  pre_tasks:
      - name: pre-run | update package cache (arch)
        tags: always
        pacman: update_cache=yes
        changed_when: false
        when: ansible_distribution == 'Archlinux'

      - name: pre-run | update package cache (debian)
        tags: always
        apt: update_cache=yes
        changed_when: false
        when: ansible_distribution in ["Debian", "Ubuntu"]

# Run roles
- hosts: all
  tags: base
  become: true
  roles:
      - base

- hosts: workstation
  tags: workstation
  become: true
  roles:
      - workstation

- hosts: server
  tags: server
  become: true
  roles:
      - server

# End of running cleanup and reporting
- hosts: all
  become: true
  tasks:
      - name: cleanup package cache (debian)
        tags: always
        apt:
            autoclean: yes
        changed_when: false
        when: ansible_distribution in ["Debian", "Ubuntu"]

      - name: autoremove orphaned packages (debian)
        tags: always
        apt:
            autoremove: yes
            purge: yes
        when: ansible_distribution in ["Debian","Ubuntu"]

      - name: send completion alert
        include_tasks: playbooks/send_completion_alert.yml
        tags: always
        when:
            - task_failed is not defined

      - name: send failure alert
        include_tasks: playbooks/send_failure_alert.yml
        tags: always
        when:
            - task_failed is defined
            - task_failed == true
