---
- name: apt_update
  apt: update_cache=yes

- name: restart_sshd
  service:
    name: "{{ openssh_service }}"
    state: restarted

- name: update_vim_bundle_perms
  file:
    path: /home/nick/.vim/bundle
    owner: nick
    group: nick
    recurse: true
