---
- name: system setup | utilities | install utility packages
  tags: packages,system,settings
  package:
    state: latest
    name:
      - at
      - colordiff
      - curl
      - htop
      - iotop
      - lsof
      - mc
      - mosh
      - ncdu
      - neofetch
      - net-tools
      - nmap
      - ranger
      - rsync
      - screen
      - sshfs
      - tmux
      - traceroute
      - "{{ vim_package }}"
      - wget
      - whois
      - zsh

- name: system setup | utilities | install man-pages (arch)
  tags: packages,system,settings
  pacman:
    state: latest
    name:
      - man-db
      - man-pages
    when: ansible_distribution == "ArchLinux"
