---
# Load distro specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  # Make sure users exist on the system
  - import_tasks: users/nick.yml

  # Set up ansible environment
  - import_tasks: ansible_setup.yml

  # Install software
  - import_tasks: software/repositories.yml
  - import_tasks: software/packages_development.yml
  - import_tasks: software/packages_utilities.yml

  rescue:
    - set_fact: task_failed=true
